baseURL = "http://example.org/"
languageCode = "en-us"
title = "Alexander Online Resume"

theme = ["nahence-cv-online"]

# Logo
[params.logo]
    src = "images/uploads/logo.png"
    alt = "Alexander Personal Resume"
    favicon = "images/uploads/favicon.png"
    appleTouchIcon = "images/uploads/apple-touch-icon.png"

# Module
[module]
  [[module.mounts]]
  source = "static"
  target = "static"

  [[module.mounts]]
  source = "node_modules/@fortawesome/fontawesome-free/webfonts"
  target = "static/webfonts"

  [[module.mounts]]
  source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
  target = "assets/vendor/js/bootstrap.bundle.min.js"
