# https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file
#
# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
publish = "public"
command = "npm install && hugo --gc --baseURL $URL"

[build.environment]
HUGO_VERSION = "0.75.1"

[context.production.environment]
HUGO_BASEURL = "https://alex-resume-online.netlify.app/"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "npm install && hugo --gc --minify --buildFuture -b $DEPLOY_URL"

[context.branch-deploy]
command = "npm install && hugo --gc --minify $DEPLOY_URL"
