backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      # Home page
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Weight', name: 'weight', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      # Footer page
      - file: "content/footer/_index.md"
        label: "Footer Section"
        name: "footer"
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

